service: tips-reminder
provider:
  name: aws
  runtime: nodejs10.x
  stage: stage, 'test'
  region: region, 'us-east-2'
  memorySize: 128
  timeout: 3

custom: ${file(./serverless/config/${opt:stage}.yaml)}
resources: ${file(./serverless/tips-reminder-resources.yaml)}

functions:
  tipsReminder:
    handler: dist/main/handler.onEvent
    name: tips-${opt:stage}-reminder
    description: > 
      Queries for tippers who are due reminders, fetches random
      recipients from appropriate tip jars and sends texts.
    runtime: nodejs12.x
    role: tips.reminder
    layers:
      - arn:aws:lambda:us-east-2:866624143450:layer:tips-common:5
    environment:
      NODE_ENV: ${opt:stage}
      TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
      TWILIO_NUMBER: ${env:TWILIO_NUMBER}
    memorySize: 128
    timeout: 3
    events:
      - schedule: cron(1 * * * ? *)
        enabled: true

package:
  exclude:
    - .npm/**
    - coverage/**
    - cloudformation/**
    - serverless/**
    - src/**
    - README.md
    - node_modules/@types/**
    - node_modules/aws-sdk/**