# TODO: Put secrets manager under cloudformation
AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloud resources for the tips-reminder service
Parameters:
  Environment:
    Type: String
    Description: The test or prod basically
    Default: test
  
Resources:
  TipsReminderRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Description: Execution role for reminder lambda
      RoleName: tips.reminder
  SecretsManagerPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: tips.reminder.secrets
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
              - "secretsmanager:GetSecretValue"
            Resource: 
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:tips-test-jwt-secret-*"
      Roles:
        - Ref: "TipsReminderRole"
  S3Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: tips.reminder.s3
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:ListObject"
            Resource:
              - "arn:aws:s3:::tips-*-reminder-integrations"
      Roles:
        - Ref: "TipsReminderRole"
  SqsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: tips.reminder.sqs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "sqs:*"
            Resource:
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tips-*-reminder"
      Roles:
        - Ref: "TipsReminderRole"
  TipsReminderIntegrationsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub tips-${Environment}-reminder-integrations
      AccessControl: BucketOwnerFullControl
  TipsReminderIntegrationsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TipsReminderIntegrationsBucket
      PolicyDocument:
        Statement:
          # reading is open to the AWS account
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: TipsReminderIntegrationsBucket
                  - "/*"
            Principal:
              AWS: !Sub ${AWS::AccountId}
  TipsReminderQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      DelaySeconds: 300
      QueueName: !Sub tips-${Environment}-reminder
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TipsReminderDLQ.Arn
        maxReceiveCount: 5
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
  TipsReminderDLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Sub tips-${Environment}-reminder-dlq
  

  
