app:
  service: tips-reminder
  jwtSecretKey: tips-test-jwt-secret
  region: us-east-2
  jwtTTL: 1h # 1hr in ms

tips:
  tippersService:
    baseUrl: https://tipsbot.us

integrations:
  - atx

lambda:
  lambdaName: tips-test-reminder